version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: evolution_postgres
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: evolution
      POSTGRES_PASSWORD: evolution_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - evolution_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7
    container_name: evolution_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - evolution_network
    restart: unless-stopped

  # Evolution API Lite
  evolution-api:
    image: atendai/evolution-api-lite:latest
    container_name: evolution_api_lite
    environment:
      # Server Configuration
      SERVER_TYPE: http
      SERVER_PORT: 8080
      SERVER_URL: http://localhost:8080  # Change this to your domain/IP
      
      # Authentication
      AUTHENTICATION_API_KEY: "WTRj!XH!.*e2WqEbuugnbq4J*c!Evp_C9DQ4xpKZ@FN8tdyg.."
      
      # CORS
      CORS_ORIGIN: "*"
      CORS_METHODS: GET,POST,PUT,DELETE
      CORS_CREDENTIALS: "true"
      
      # Logging
      LOG_LEVEL: ERROR,WARN,DEBUG,INFO,LOG,VERBOSE
      LOG_COLOR: "true"
      LOG_BAILEYS: error
      
      # Database
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: 'postgresql://evolution:evolution_password@postgres:5432/evolution?schema=public'
      
      # Cache
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: redis://redis:6379
      CACHE_REDIS_PREFIX_KEY: evolution_api
      
      # Instance Management
      DEL_INSTANCE: "false"
      
      # Events
      EVENT_EMITTER_MAX_LISTENERS: 50
      
      # Disable integrations (Lite version)
      WEBHOOK_GLOBAL_ENABLED: "true"
      WEBHOOK_GLOBAL_URL: ""  # Set your webhook URL here
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: "false"
      
      # S3 (disabled for lite)
      S3_ENABLED: "false"
      
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - evolution_network
    restart: unless-stopped
    volumes:
      - evolution_instances:/evolution/instances

  # Evolution Manager
  evolution-manager:
    image: atendai/evolution-manager:latest
    container_name: evolution_manager
    environment:
      # Manager Configuration
      NEXT_PUBLIC_MANAGER_NAME: "Evolution Manager"
      
      # API Connection
      NEXT_PUBLIC_EVOLUTION_API_URL: http://evolution-api:8080
      AUTHENTICATION_API_KEY: "WTRj!XH!.*e2WqEbuugnbq4J*c!Evp_C9DQ4xpKZ@FN8tdyg.."
      
      # Database
      DATABASE_URL: postgresql://evolution:evolution_password@postgres:5432/evolution?schema=public
      
      # NextAuth
      NEXTAUTH_URL: http://localhost:3000  # Change this to your manager URL
      NEXTAUTH_SECRET: "LizULWkrv_o84Qd*xkTX_n.tmj68R6w-"
      
    ports:
      - "3000:3000"
    depends_on:
      - evolution-api
      - postgres
    networks:
      - evolution_network
    restart: unless-stopped

networks:
  evolution_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  evolution_instances:
